### ISSUE TITLE
Mac ogar problem cant find "index.js"

### ISSUE THREAD

**Issue by x38** [OgarProject/Ogar#187]
I seem to not be able to start because of this:
bash-3.2# node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/admin/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by Ephemerality** [comment]
You didn't `cd` into the src directory within the Ogar folder.

**Comment by x38** [comment]
what is cd?

**Comment by maixuanhan** [comment]
**change directory**?
