### ISSUE TITLE
game wont start

### ISSUE THREAD

**Issue by Creeperman8362** [OgarProject/Ogar#224]
FYI i has node installed

C:\Users\null\programs\Ogar-master\src>node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\dylan\programs\Ogar-master\src\GameServer.js
:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

C:\Users\null\programs\Ogar-master\src>pause
Press any key to continue . . .

**Comment by devcem** [comment]
Write console, 
npm install websocket or npm install ws

**Comment by miketorman** [comment]
I'm having the same issue. tried the fix but still same error.

**Comment by NatsuTheGreat** [comment]
Open up your command prompt and type:

*npm install ws*

Then you get text with some words highlighted in yellow/purple. This means it was successfully installed and you should be good to go,

**Comment by MastaCoder** [comment]
@vram4 You might want to close this. It's not really relevant to Ogar and hasn't had a response for 15 days.
