### ISSUE TITLE
Make this work on heroku

### ISSUE THREAD

**Issue by luckcolors** [OgarProject/Ogar#23]
Hello.
I'm trying to start the app on heroku.
heroku doesn't work with ports not declared as:
process.env.PORT || 80;
Could you please fix this?
docs: https://devcenter.heroku.com/articles/node-websockets

**Comment by Ephemerality** [comment]
I'm not entirely sure why it would be necessary. If process.env.PORT isn't empty it will use that value, other it will use the port specified. The port can be overridden with the config file anyway, though.  
Does Heroku just not run the application at all if process.env.PORT isn't in there?

**Comment by maixuanhan** [comment]
What do you do on your server? Please provide `heroku config` output.
Do you make any change in the code or configure. I'll try to deploy a server on **Heroku** to verify this.

**Comment by luckcolors** [comment]
ok sorry for replaying now as you asked here is the out: dry-mesa-8322 has no config vars.
Procfile: web: node src/index.js
Log:2015-07-02T13:54:45.432636+00:00 heroku[web.1]: State changed from crashed to st
arting
2015-07-02T13:54:48.431700+00:00 heroku[web.1]: Starting process with command `n
ode src/index.js`
2015-07-02T13:54:50.717180+00:00 app[web.1]: Detected 512 MB available memory, 5
12 MB limit per process (WEB_MEMORY)
2015-07-02T13:54:50.717271+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-02T13:54:51.476680+00:00 app[web.1]: events.js:85
2015-07-02T13:54:51.476685+00:00 app[web.1]:       throw er; // Unhandled 'error
' event
2015-07-02T13:54:51.476687+00:00 app[web.1]:             ^
2015-07-02T13:54:51.476688+00:00 app[web.1]: Error: listen EACCES
2015-07-02T13:54:51.476690+00:00 app[web.1]:     at exports._errnoException (uti
l.js:746:11)
2015-07-02T13:54:51.476691+00:00 app[web.1]:     at Server._listen2 (net.js:1139
:19)
2015-07-02T13:54:51.476693+00:00 app[web.1]:     at listen (net.js:1182:10)
2015-07-02T13:54:51.476696+00:00 app[web.1]:     at GameServer.startStatsServer
(/app/src/GameServer.js:899:21)
2015-07-02T13:54:51.476694+00:00 app[web.1]:     at Server.listen (net.js:1267:5
)
2015-07-02T13:54:51.476698+00:00 app[web.1]:     at GameServer.start (/app/src/G
ameServer.js:194:10)
2015-07-02T13:54:51.476701+00:00 app[web.1]:     at Module._compile (module.js:4
60:26)
2015-07-02T13:54:51.476699+00:00 app[web.1]:     at Object.<anonymous> (/app/src
/index.js:25:12)
2015-07-02T13:54:51.476702+00:00 app[web.1]:     at Object.Module._extensions..j
s (module.js:478:10)
2015-07-02T13:54:51.476704+00:00 app[web.1]:     at Module.load (module.js:355:3
2)
2015-07-02T13:54:51.416544+00:00 app[web.1]: [Game] Ogar - An open source Agar.i
o server implementation

**Comment by maixuanhan** [comment]
I had updated my answer before. Now I see that you face same problem: `EACCES`

**Comment by subv3rsion** [comment]
Hello,

We are no longer offering support on the Ogar issue tracker hosted here at GitHub. If you wish to obtain support, you may do so by visiting our community forums/website, which can be found here: www.ogarproject.com

Once registered, you may post in the General Support section for Ogar 1.0, make suggestions, and search a variety of other problems experienced by other members on the forums.

**Comment by MahdiIsRootin** [comment]
_If That Happend To You DO tHIS
-Open the start.sh or start.bat what ever you use
-open it so u can edit it with notepad
-and replace:



#!/bin/bash
if pwd | grep -qw "src"; then
node --expose-gc index.js
else
echo "You must run Ogar Unlimited from the src folder!"
fi
Use # Instead----------------------------------------With---------------------------------
#!/bin/bash
if pwd | grep -qw "src"; then
sudo node --expose-gc index.js
else
echo "You must run Ogar Unlimited from the src folder!"
fi
so u can replace
node --expose-gc index.js
with
sudo node --expose-gc index.js



If This Worked Please Reply Me ......................

**Comment by ItzLevvie** [comment]
You don't need that many codes to run a server..
```sudo node index.js``` will work just fine
