### ISSUE TITLE
Ogar Teams server problem?

### ISSUE THREAD

**Issue by High44** [OgarProject/Ogar#235]
It seems whenever I put teams gamemode and if I add more then 8 bots it comes up with a crazy error - 
TypeError: Cannot read property 'position' of undefined
    at Cell.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+e+n+t+i+t+y+\+P+l+a+y+e+r+C+e+l+l+.+j+s.PlayerCell.simpleCollide (<anonymous>)
    at Mode.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+g+a+m+e+m+o+d+e+s+\+T+e+a+m+s+.+j+s.Teams.onCellMove (<anonymous>)
    at Cell.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+e+n+t+i+t+y+\+P+l+a+y+e+r+C+e+l+l+.+j+s.PlayerCell.calcMove (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+G+a+m+e+S+e+r+v+e+r+.+j+s.GameServer.updateMoveEngine (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+G+a+m+e+S+e+r+v+e+r+.+j+s.GameServer.cellTick (<anonymous>)
    at GameServer.Math.Enclose.+c+:+\+t+h+e+b+o+x+\+P+r+o+g+r+a+m+ +F+i+l+e+s+ +(+x+8+6+)+\+J+e+n+k+i+n+s+\+j+o+b+s+\+O+g+a+r+ +-+ +W+i+n+3+2+\+w+o+r+k+s+p+a+c+e+\+s+r+c+\+G+a+m+e+S+e+r+v+e+r+.+j+s.GameServer.mainLoop (<anonymous>)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

Anyone know why?
>

**Comment by 14anthony7095** [comment]
Are you using newest version?

**Comment by Agarian** [comment]
Your server is either outdated or the gamemode was tampered with.

**Comment by vram4** [comment]
>Your server is either outdated or the gamemode was tampered with.
Pretty much that ^.

Closing this issue.
