### ISSUE TITLE
the food growth addition (in experimental) seems to break the server? why?

### ISSUE THREAD

**Issue by Agarian** [OgarProject/Ogar#344]
**If gamemode = 2 or 14 (experimental & experimental team)then the server crashes? idk why but when it it gonna be fixed?:**
TypeError: Cannot read property 'config' of undefined
    at Cell.Food (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\entity\Food.js:11:24)
    at Cell.MotherCell.spawnFood (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\gamemodes\Experimental.js:234:13)
    at Cell.MotherCell.update (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\gamemodes\Experimental.js:164:18)
    at Mode.Experimental.updateMotherCells (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\gamemodes\Experimental.js:36:16)
    at Mode.Experimental.onTick (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\gamemodes\Experimental.js:113:11)
    at GameServer.gamemodeTick (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\GameServer.js:367:19)
    at GameServer.mainLoop (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\plain ogar variations\Ogar-master food growth\Ogar-master\src\GameServer.js:387:29)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by mrmarktyy** [comment]
@Agarian just made a PR to fix the issue. #350
