### ISSUE TITLE
Error when trying to run:  Error: listen EACCES

### ISSUE THREAD

**Issue by retep-mathwizard** [OgarProject/Ogar#388]
at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1139:19)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at GameServer.startStatsServer (/home/retep/Ogar/src/GameServer.js:949:21)
    at GameServer.start (/home/retep/Ogar/src/GameServer.js:210:10)
    at Object.<anonymous> (/home/retep/Ogar/src/index.js:25:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
[Error] Please make sure you are running Ogar with root privileges.
Please help!

**Comment by Luka967** [comment]
Start Ogar in Administrator mode.

**Comment by ItzLevvie** [comment]
Use ```sudo node Ogar``` instead of ```node Ogar```.

**Comment by Luka967** [comment]
didn't notice `/home/retep/...`, that is Linux, right?

**Comment by ItzLevvie** [comment]
Yes. @Luka967

**Comment by MahdiIsRootin** [comment]
ItzLevvie Your Answer Accualy Helped Open The Start.sh with in u can edit it
#!/bin/bash
if pwd | grep -qw "src"; then
    node --expose-gc index.js
else
    echo "You must run Ogar Unlimited from the src folder!"
fi
Use Instead---------------------------------------------------------------------------------
#!/bin/bash
if pwd | grep -qw "src"; then
    sudo node --expose-gc index.js
else
    echo "You must run Ogar Unlimited from the src folder!"
fi
so u can replace
node --expose-gc index.js
with
sudo node --expose-gc index.js

**Comment by ItzLevvie** [comment]
Also ```sudo node index.js``` will work just fine, there is actually no need to copy Ogar-unlimited's index.js.
