### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Cyphrz** [OgarProject/Ogar#419]
>TypeError: Cannot read property 'cells' of undefined
    at PlayerTracker.getSpectateNodes (/home/fliptech/ogar1-30/Ogar/src/PlayerTracker.js:305:41)
    at PlayerTracker.calcViewBox (/home/fliptech/ogar1-30/Ogar/src/PlayerTracker.js:266:21)
    at PlayerTracker.update (/home/fliptech/ogar1-30/Ogar/src/PlayerTracker.js:135:31)
    at GameServer.updateClients (/home/fliptech/ogar1-30/Ogar/src/GameServer.js:447:39)
    at GameServer.mainLoop (/home/fliptech/ogar1-30/Ogar/src/GameServer.js:405:14)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
Release from 1/30/16

**Comment by Luka967** [comment]
Got the issue. Will update pull request soon.

**Comment by Luka967** [comment]
Oh and also, nice XANA picture.

**Comment by Cyphrz** [comment]
Heh,

Thanks

**Comment by NatsuTheGreat** [comment]
@Luka967 Yeah please fix it man xD I really want that spectate mode instead of the other annoying one

**Comment by NatsuTheGreat** [comment]
@vram4 close
