### ISSUE TITLE
how random color split

### ISSUE THREAD

**Issue by mafiakb** [OgarProject/Ogar#421]
please any?

**Comment by NatsuTheGreat** [comment]
Again, someone had an issue with ejected mass.

Do this:
Find the *splitCells* function in GameServer.js and add this

````
split.setColor(cell.getColor());
````
after all the other functions. It about line 610 - 650

**Comment by Andrews54757** [comment]
uh by the way, cell.getcolor() wont work. I used this.getRandomColor()

**Comment by NatsuTheGreat** [comment]
He didn't word it very well, I thought he meant how to make them stop being random colors, if he wants random colors, then yes he will  have to use this.getRandomColor()

**Comment by Andrews54757** [comment]
Also, there is no such thing as split.SetColor

**Comment by NatsuTheGreat** [comment]
setColor*

**Comment by mafiakb** [comment]
thank you :) work for me :D this.getRandomColor()

**Comment by Agarian** [comment]
TypeError: Cannot read property 'setColor' of undefined
    at GameServer.splitCells (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:885:14)
    at Mode.pressSpace (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\gamemodes\Mode.js:273:20)
    at PlayerTracker.update (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\PlayerTracker.js:103:34)
    at GameServer.updateClients (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:694:39)
    at GameServer.mainLoop (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:643:14)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Andrews54757** [comment]
See, there is no thing as split.setColor

**Comment by Agarian** [comment]
then whats the correct function?

**Comment by NatsuTheGreat** [comment]
@Andrews54757 I told you :$

**Comment by NatsuTheGreat** [comment]
@Agarian what are you trying to do

**Comment by Agarian** [comment]
og he means setColor(this.getRandomColor())

**Comment by NatsuTheGreat** [comment]
Yeah. If you wanted random color splits

**Comment by Agarian** [comment]
nvm:
ReferenceError: setColor is not defined
    at GameServer.splitCells (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:905:3)
    at Mode.pressSpace (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\gamemodes\Mode.js:273:20)
    at PlayerTracker.update (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\PlayerTracker.js:103:34)
    at GameServer.updateClients (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:695:39)
    at GameServer.mainLoop (C:\Users\owner\Desktop\Agar.io Stuff\Private servers\Ogar-devs\Ogar-unlimited-master\src restartcommand\GameServer.js:644:14)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Agarian** [comment]
The full function for random color split is?

**Comment by NatsuTheGreat** [comment]
I new I fricking had it somewhere I just can't find it

**Comment by NatsuTheGreat** [comment]
@vram4 Close?

**Comment by Agarian** [comment]
Um this is still open? But i was thinking of making this a config in ogarUL. So does any1 have a working function that allows this?

**Comment by SimonOrJ** [comment]
If you are running the latest version of Ogar, modify this line:
https://github.com/OgarProject/Ogar/blob/master/src/NodeHandler.js#L234
`    newCell.setColor(parent.getColor());`
to
`    newCell.setColor(parent.this.gameServer.getRandomColor());`

**Comment by Luka967** [comment]
^
