### ISSUE TITLE
Everytime I pop myself on a Virus my server crashes? 

### ISSUE THREAD

**Issue by AGServers** [OgarProject/Ogar#426]
Here is an Image and text to show what it says exactly in console : 

at Cell.Virus.onConsume (/home/admin/Ogar/src/entity/Virus.js:61:17)
    at GameServer.updateMoveEngine (/home/admin/Ogar/src/GameServer.js:577:19)
    at GameServer.cellTick (/home/admin/Ogar/src/GameServer.js:366:10)
    at GameServer.mainLoop (/home/admin/Ogar/src/GameServer.js:399:29)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)

IMAGE:

https://gyazo.com/65b312843f122a4142cc6b0c79807576

**Comment by Luka967** [comment]
You're using the latest version right?
