### ISSUE TITLE
[Question/Help] Incorrect path to nodejs?

### ISSUE THREAD

**Issue by Redstone-Pro-73** [OgarProject/Ogar#442]
How do I change the path to where I installed nodejs 0.6.9? I also have ws installed in /usr/bin/
I have even tried running `node index.js` but I get: 
`node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module 'ws'
    at Function._resolveFilename (module.js:334:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/agario/rcn/Ogar/src/GameServer.js:2:17)
    at Module._compile (module.js:444:26)
    at Object..js (module.js:462:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Module.require (module.js:357:17)
`
So I am not sure what todo. Please help asap!

**Comment by Redstone-Pro-73** [comment]
This also appears in the npm-debug.log

**Comment by vram4** [comment]
Make sure you have installed the ws module by using `npm install ws`

**Comment by NatsuTheGreat** [comment]
@vram4 Close?
