### ISSUE TITLE
I also got this when spectating.

### ISSUE THREAD

**Issue by NatsuTheGreat** [OgarProject/Ogar#501]
>TypeError: Cannot read property 'x' of undefined
    at PlayerTracker.getSpectateNodes (C:\Users\Downloads\Ogar-master2\Ogar-master2\src\PlayerTracker.js:312:47)
    at PlayerTracker.calcViewBox (C:\Users\Downloads\Ogar-master2\Ogar-master2\src\PlayerTracker.js:281:21)
    at PlayerTracker.update (C:\Users\Downloads\Ogar-master2\Ogar-master2\src\PlayerTracker.js:128:31)
    at GameServer.updateClients (C:\Users\Downloads\Ogar-master2\Ogar-master2\src\GameServer.js:478:39)
    at GameServer.mainLoop (C:\Users\Downloads\Ogar-master2\Ogar-master2\src\GameServer.js:434:14)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by NatsuTheGreat** [comment]
Solved it.
