### ISSUE TITLE
Fix?

### ISSUE THREAD

**Issue by DerpyUnlimited** [OgarProject/Ogar#543]
`Error: Cannot find module 'vector2-node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Clyde\Desktop\Ogar-master\src\ai\BotPlayer.js:3:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)`

**Comment by ItzLevvie** [comment]
Do ```npm install vector2-node```

**Comment by DerpyUnlimited** [comment]
@ItzLevvie thanks!
