### ISSUE TITLE
Cannot find module 'vector2-node'

### ISSUE THREAD

**Issue by ThatOneGuyOnline** [OgarProject/Ogar#549]
I'm on OS X El Capitan (10.11.3) I'm getting this error message repeatedly
bash-3.2# node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'vector2-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/fazebigboy/Downloads/Ogar-master/src/ai/BotPlayer.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by Andrews54757** [comment]
@Luka967 i told you that the prev pr will cause people to be confused

**Comment by Andrews54757** [comment]
to "fix" do npm install vector2-node

**Comment by ItzLevvie** [comment]
Close? @vram4

**Comment by LikeABoka363** [comment]
Im getting this as well, This is all I do in my terminal, I'm on a mac: 
Last login: Thu Apr 28 19:02:20 on console
Claires-iMac:~ Boka$ cd /Users/Boka/Desktop/Ogar-master/src 
Claires-iMac:src Boka$ npm install ws
npm WARN package.json Ogar@1.0.0 license should be a valid SPDX license expression
ws@1.1.0 ../node_modules/ws
├── options@0.0.6
└── ultron@1.0.2
Claires-iMac:src Boka$ sudo -s
Password:
bash-3.2# node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'vector2-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Boka/Desktop/Ogar-master/src/ai/BotPlayer.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
bash-3.2# 

If anyone can help that would be great!

**Comment by ItzLevvie** [comment]
do ```npm install vector2-node``` on your mac terminal

**Comment by LikeABoka363** [comment]
I did

**Comment by LikeABoka363** [comment]
It hasn't helped

**Comment by LikeABoka363** [comment]
Can you tell me exactly what I have to do in terminal to make it?

**Comment by LikeABoka363** [comment]
Last login: Thu Apr 28 19:45:04 on ttys000
Claires-iMac:~ Boka$ npm install vector2-node
vector2-node@0.0.3 node_modules/vector2-node
Claires-iMac:~ Boka$ 
Thats all it does, I retry it and it still wont work

**Comment by ItzLevvie** [comment]
What error do you get when running node index.js?

**Comment by LikeABoka363** [comment]
It works now, I watched a few videos on how to fix it! Thanks for your help!
