### ISSUE TITLE
**MAJOR PROBLEM**

### ISSUE THREAD

**Issue by ThomasIO** [OgarProject/Ogar#554]
When I start my server on my iMac it seems to not work.

SPECS
iMac (21.5-inch, Late 2013)
Processor 3.1 GHz Intel Core i7
Memory 16 GB 1600 MHz DDR3
Graphics NVIDIA GeForce GT 750M 1024 MB
OSX El Capitan

My method of starting the server:
For this method you need nodejs. (www.nodejs.org)

1. Open Terminal.
2. type "cd /Users/thomas/Desktop/AgarSERVER/src "
3. I then type "npm install ws". I wait for it to install.
4. I type "sudo -s" and type in my password.
5. I then afterwards type "node index.js", and get this error.

    throw err;
    ^

Error: Cannot find module 'vector2-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thomas/Desktop/AgarSERVER/src/ai/BotPlayer.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

How do I fix this? Thanks.

**Comment by NatsuTheGreat** [comment]
Not really a major problem lmao... But do this:
````
npm install vector2-node
````

**Comment by ThomasIO** [comment]
bash-3.2# node index.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/thomas/Desktop/Ogar-master/src/GameServer.js:2:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by ThomasIO** [comment]
Nevermind! You have do do both! Thanks!

**Comment by Agarian** [comment]
Close?

**Comment by mrsegen** [comment]
I'm having the same problem on Windows 8.1, using NodeJSPortable. When I try the `npm install vector2-node` command, I receive the error: `'node' is not recognized as an internal or external command, operable program or batch file.`

**Comment by celiandu61** [comment]
You need to add NodeJS to PATH i think http://stackoverflow.com/a/27864253

**Comment by mrsegen** [comment]
I'm testing this on a managed device that seems to auto-revert changes to the PATH variable. 

For anyone else trying this in similar circumstances, I could start the server by doing the following

1. Directly open the NodeJSPortable.exe
2. Enter `npm install ws` and `npm install vector2-node` if needed
3. Navigate to the location of `index.js` by entering `cd ..\..\path\to\Ogar\src`
4. Enter `node index.js.`

The server should then be started. In my case, though, it seems firewall settings prevent accessing from the browser. (I cannot change firewall settings on this managed PC.)
