### ISSUE TITLE
Teams mode doesn't work.

### ISSUE THREAD

**Issue by lukerayman** [OgarProject/Ogar#579]
When I try to start server in Teams mode I'm getting this error:
```
[Game] Ogar - An open source Agar.io server implementation
[Game] Loaded stats server on port 8082
[Game] Listening on port 8081
[Game] Current game mode is Teams
>TypeError: Cannot read property 'playerTracker' of undefined
    at GameServer.mainLoop (/home/ubuntu/workspace/src/GameServer.js:417:52)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by lukerayman** [comment]
OK, I fixed it byt checking if `clients[0]` isn't null.

**Comment by lukerayman** [comment]
It can be fixed by adding check for `clients[0]`:

```
if (clients[0]) {
    this.largestClient = clients[0].playerTracker;
}
```

**Comment by Megabyte918** [comment]
make a pr
