### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by dl8sd11** [OgarProject/Ogar#587]
I got an error with ogar server on Windows. I can run this just a mounth ago.

at first......
![image](https://cloud.githubusercontent.com/assets/19171021/15453009/4c43d11a-2036-11e6-8f4a-da0952d4364e.png)
then i got...... 
![image](https://cloud.githubusercontent.com/assets/19171021/15453027/b3bb0ad4-2036-11e6-8f8d-7eb2a5a50bb1.png)

![image](https://cloud.githubusercontent.com/assets/19171021/15453004/1bbd3054-2036-11e6-981f-10dbbc2e2773.png)

agario.core.js:7 exception thrown: IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-21243) is negative.,Error: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-21243) is negative.
    at Error (native)
    at Array.<anonymous> (http://agar.io/agario.core.js:9:7751)
    at c.Ja._4f4d9108 (http://agar.io/agario.core.js:10:14701)
    at _c (http://agar.io/agario.core.js:11:79849)
    at Ec (http://agar.io/agario.core.js:11:47478)
    at Vb (http://agar.io/agario.core.js:11:12287)
    at Array.Ub (http://agar.io/agario.core.js:11:12023)
    at Br (http://agar.io/agario.core.js:14:2655)
    at Object.m.C (http://agar.io/agario.core.js:7:5793)
    at http://agar.io/agario.core.js:6:495c.printErr @ agario.core.js:7
agario.core.js:9 Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-21243) is negative.e.e.$a @ agario.core.js:9Ra.e.e.aa @ agario.core.js:6
master.js:5 trying to refresh a non dfp ad. continue

**Comment by firelightning13** [comment]
It's not working yet

**Comment by dl8sd11** [comment]
why? will it work in these days?

**Comment by ItzLevvie** [comment]
Read https://github.com/OgarProject/Ogar/issues/588

**Comment by dl8sd11** [comment]
but i can't found those code in the latest code of ogar

**Comment by dl8sd11** [comment]
can u help me? i made some changes on the server for our joint show next week. but now i can't even connect the server

**Comment by NullSomething** [comment]
Please help me!!!! 

screen image = http://i.hizliresim.com/B2yvAp.jpg

**Comment by NullSomething** [comment]
Can u clarify? Ogar?

**Comment by SimonOrJ** [comment]
You're writing on Ogar's issues.  [MultiOgar](https://github.com/Barbosik/MultiOgar) is BarbosIk's fork of Ogar, which is really well optimized.

You can download the entire project, unzip it, run "install_dependencies.bat", then run "start-windows.bat" inside the src folder.  The process is the same for the two.

**Comment by NullSomething** [comment]
Not opened.Please help me

screen image= http://i.hizliresim.com/NEZW6g.jpg

**Comment by Barbosik** [comment]
just press on "Play" button :)
And you cannot connect to facebook, because facebook is blocked by your adblock

**Comment by NullSomething** [comment]
Solution???

**Comment by NullSomething** [comment]
PLS TUTORİAL

**Comment by ItzLevvie** [comment]
Download https://github.com/Barbosik/MultiOgar/archive/master.zip

**Comment by NullSomething** [comment]
after??

**Comment by ItzLevvie** [comment]
Extract the master.zip then go to MultiOgar-master, double click on "Install Dependencies.bat". then go to the src folder and double click on Start-windows.bat to start the server.

**Comment by NullSomething** [comment]
screen image = 1  http://i.hizliresim.com/B2LO1L.jpg
                          2  http://i.hizliresim.com/6nJD19.jpg

**Comment by ItzLevvie** [comment]
Show your full window

**Comment by NullSomething** [comment]
Problem  :(  = http://www.mediafire.com/download/z9nmbc118dqe0ga/helpp.avi
