### ISSUE TITLE
Bots are broken on Windows version..

### ISSUE THREAD

**Issue by Shad0wGeneral** [OgarProject/Ogar#592]
>[Game] Loaded stats server on port 88
[Game] Listening on port 446
[Game] Current game mode is Free For All
>addbot 1
[Console] Added 1 player bots
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
TypeError: Cannot read property 'indexOf' of undefined
    at GameServer.removeNode (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:343:29)
    at GameServer.cellEating (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:653:14)
    at GameServer.updateMoveEngine (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:625:18)
    at GameServer.moveTick (C:\Servers\Agar.io\Ogar-master\Ogar-master\src\GameServer.js:365:10)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
<

**Comment by ItzLevvie** [comment]
Use @Luka967's version: https://github.com/Luka967/Ogar
