### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by Prime55** [OgarProject/Ogar#623]
I just installed a fresh version, didn't change a single config but when i go to `http://agar.io/?ip=127.0.0.1:443`and click to play i get this: 
![download 1](https://cloud.githubusercontent.com/assets/18355005/16205997/cd249c88-36fc-11e6-9a0c-11b50cee4942.png)

**What do i have to do ?**

**Comment by ItzLevvie** [comment]
Download https://github.com/Luka967/Ogar/archive/master.zip

**Comment by Prime55** [comment]
@ItzLevvie Downloaded, didn't change nothing, clicked to play and got this:

`[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
ReferenceError: Vector is not defined
    at GameServer.spawnPlayer (C:\Users\Thiago\Desktop\Nova pasta (2)\Ogar-master\src\GameServer.js:400:24)
    at Mode.FFA.onPlayerSpawn (C:\Users\Thiago\Desktop\Nova pasta (2)\Ogar-master\src\gamemodes\FFA.js:75:16)
    at PacketHandler.setNickname (C:\Users\Thiago\Desktop\Nova pasta (2)\Ogar-master\src\PacketHandler.js:124:34)
    at PacketHandler.handleMessage (C:\Users\kasjfkajfkja\Desktop\Nova pasta (2)\Ogar-master\src\PacketHandler.js:59:22)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (C:\Users\kasjfkajfkja\node_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\kasjfkajfkja\node_modules\ws\lib\Receiver.js:537:18
    at Receiver.applyExtensions (C:\Users\kasjfkajfkja\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\kasjfkajfkja\node_modules\ws\lib\Receiver.js:531:14`

**Comment by Prime55** [comment]
Didn't change nothing and got this when clicked to play: @ItzLevvie 

`[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
ReferenceError: Vector is not defined
    at GameServer.spawnPlayer (C:\Users\---\Desktop\Ogar)\Ogar-master\src\GameServer.js:400:24)
    at Mode.FFA.onPlayerSpawn (C:\Users\---\Desktop\Ogar)\Ogar-master\src\gamemodes\FFA.js:75:16)
    at PacketHandler.setNickname (C:\Users\---\Desktop\Ogar\Ogar-master\src\PacketHandler.js:124:34)
    at PacketHandler.handleMessage (C:\Users\---\Desktop\Ogar\Ogar-master\src\PacketHandler.js:59:22)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.onbinary (C:\Users\---\node_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\---\node_modules\ws\lib\Receiver.js:537:18
    at Receiver.applyExtensions (C:\Users\--\node_modules\ws\lib\Receiver.js:364:5)
    at C:\Users\---\node_modules\ws\lib\Receiver.js:531:14`

**Comment by SimonOrJ** [comment]
You need to run `install dependencies.bat` before you run the server.  If you did run that, then try downloading it from Levvie's link again.  MultiOgar was updated a few times between the time you posted the last comment and now.

**Comment by Luka967** [comment]
https://github.com/Luka967/Ogar/archive/patch-1.zip this one should work

**Comment by Agarian** [comment]
close?

**Comment by Prime55** [comment]
@Luka967 Yep.
