### ISSUE TITLE
Getting Weird Error

### ISSUE THREAD

**Issue by DaAwesomeRazor** [OgarProject/Ogar#635]
TypeError: Cannot read property '0' of undefined
    at PlayerTracker.update (C:\Users\Razor\Desktop\Ogar\Ogar-master\src\PlayerTracker.js:135:60)
    at PlayerHandler.update (C:\Users\Razor\Desktop\Ogar\Ogar-master\src\PlayerHandler.js:19:34)
    at GameServer.mainLoop (C:\Users\Razor\Desktop\Ogar\Ogar-master\src\GameServer.js:364:24)
    at Timer.listOnTimeout (timers.js:92:15)
TypeError: Cannot read property '0' of undefined

I tried core.disableIntegrityChecks(true), still doesnt work

**Comment by Luka967** [comment]
Remove line 135 from that file it'll work fine.
