### ISSUE TITLE
Cannot find module  ؟ WTF

### ISSUE THREAD

**Issue by HEROx29** [OgarProject/Ogar#650]
Error: Cannot find module '/root/Ogar-master/Ogar'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
root@node-1gb-ams2-01:~/Ogar-master# node Ogar
module.js:327
    throw err;
    ^

Error: Cannot find module '/root/Ogar-master/Ogar'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by Barbosik** [comment]
you need to run the server from server directory.
For exampel, if you clonned ogar server into forlder /home/<username>/Ogar
Then you need to execute:
```
cd /home/<username>/Ogar
npm install
node src/index.js
```

where <username> is your system username

**Comment by HEROx29** [comment]
thx

**Comment by IAP-Reloaded** [comment]
This needs to be closed.
