### ISSUE TITLE
Allow non-interactive mode

### ISSUE THREAD

**Issue by aanno** [OgarProject/Ogar#690]
Currently ogar is spawning a asyncconsole. When I try to start it with no TTY attached

/usr/bin/node src/index.js </dev/null

the following error appears:

TypeError: this.stdin.setRawMode is not a function
    at new AsyncConsole (/home/ogar/Ogar/node_modules/asyncconsole/index.js:24:12)
    at Timeout._onTimeout (/home/ogar/Ogar/src/index.js:50:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

This is because setRawMode is only available for TTYs (see https://github.com/nodejs/node-v0.x-archive/issues/8204)

Please allow to start ogar non-interactive, i.e. without an asyncconsole.

**Comment by Luka967** [comment]
Use [this version of the index.js](https://github.com/OgarProject/Ogar/blob/aa7de2509fadc0add4082a2807fcd01e6597bf28/src/index.js).

**Comment by Andrews54757** [comment]
@aanno Actually, there is a mode. Do `node index.js --noconsole`
