### ISSUE TITLE
> TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by universebound** [OgarProject/Ogar#703]
[Game] Ogar - An open source Agar.io server implementation
[Game] Loaded 0 plugin(s)
[Game] Listening on port 281
[Game] Current game mode is Free For All
[Game] Loaded stats server on port 88
> TypeError: Cannot read property 'headers' of undefined
    at GameServer.connectionEstablished (C:\Users\Hp\Downloads\Ogar-master\Ogar-master\src\GameServer.js:219:35)
    at emitTwo (events.js:125:13)
    at WebSocketServer.emit (events.js:213:7)
    at handleUpgrade (C:\Users\Hp\Downloads\Ogar-master\Ogar-master\node_modules\ws\lib\WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (C:\Users\Hp\Downloads\Ogar-master\Ogar-master\node_modules\ws\lib\WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (C:\Users\Hp\Downloads\Ogar-master\Ogar-master\node_modules\ws\lib\WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (C:\Users\Hp\Downloads\Ogar-master\Ogar-master\node_modules\ws\lib\WebSocketServer.js:87:14)
    at emitThree (events.js:135:13)
    at Server.emit (events.js:216:7)
    at onParserExecuteCommon (_http_server.js:494:14)

**Comment by ialexsip** [comment]
comment ( // ) from line 219 to 229.

**Comment by KidNode** [comment]
If you read the comments above the code that is giving errors, it says that if you try to disable to certain code legal action may be taken against you. I'm still trying to fix this bug by replacing the line: var origin = ws.UpgradeReq.headers.origin to the actual origin varible in the object of ws. This just boils down to that UpgradeReq is deprecated or removed.

**Comment by Festum** [comment]
Me too

```
 nestor build usercity_my_provider_portal_apse1_secured [""] --console
Job usercity_my_provider_portal_apse1_secured was triggered successfully
/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/lib/cli/job.js:191
          var buildUrl = response.headers.location;
                                 ^

TypeError: Cannot read property 'headers' of undefined
    at cb (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/lib/cli/job.js:191:34)
    at Object.<anonymous> (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/lib/api/util.js:81:5)
    at /home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/bagofrequest/lib/bagofrequest.js:86:41
    at done (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/bagofrequest/lib/bagofrequest.js:149:5)
    at /home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/async/dist/async.js:906:16
    at next (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/async/dist/async.js:2995:18)
    at Request._callback (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/bagofrequest/lib/bagofrequest.js:134:9)
    at Request.self.callback (/home/festum/.nvm/versions/node/v8.5.0/lib/node_modules/nestor/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)

```

**Comment by ItzLevvie** [comment]
@KidNode You still want to solve the issue?

**Comment by ChikoxD** [comment]
I have the same problem. any solution?

**Comment by ItzLevvie** [comment]
@ChikoxD https://github.com/OgarProject/Ogar/issues/707#issuecomment-341902434
