### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by willthepill** [OgarProject/Ogar#706]
Hi, im not very good with code and things like that, but i tried before and did it and that was months ago. I have a problem. here is what shows up after i type node index.js into terminal. 

> TypeError: Cannot read property 'headers' of undefined
    at GameServer.connectionEstablished (/Users/willchamberlain/Desktop/Ogar-master/src/GameServer.js:219:35)
    at emitTwo (events.js:106:13)
    at WebSocketServer.emit (events.js:191:7)
    at handleUpgrade (/Users/willchamberlain/Desktop/Ogar-master/node_modules/ws/lib/WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (/Users/willchamberlain/Desktop/Ogar-master/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/Users/willchamberlain/Desktop/Ogar-master/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (/Users/willchamberlain/Desktop/Ogar-master/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)

any solutions?

**Comment by Cloudftw** [comment]
i got the same thing. don't worry about it. private servers dont work anymore.

**Comment by willthepill** [comment]
ok, I'm using open agar now, it works better

**Comment by ZfsrGhS953** [comment]
@willthepill **You may have malware on your computer!** This is a serious warning, no one except Andrews54757 knows what's in the obfuscated files. Quickly delete ClosedAgar (OpenAgar) and run an antivirus scan. For now, use [MultiOgar-Edited](https://github.com/Megabyte918/MultiOgar-Edited) until I finish Bacter2, which will be literally a hundred times faster than ClosedAgar.

**Comment by Faris90** [comment]
Openagar is shit

**Comment by Fan7asy** [comment]
Delete these [lines](https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L211#L230).
It should all work fine afterwards.

**Comment by HenrikAndWiktor** [comment]
Delete lines 211-230.
