### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Faris90** [OgarProject/Ogar#707]
when I try to join my server on a custom client:
TypeError: Cannot read property 'headers' of undefined
    at GameServer.connectionEstablished (/home/ubuntu/workspace/src/GameServer.js:219:35)
    at emitTwo (events.js:106:13)
    at WebSocketServer.emit (events.js:191:7)
    at handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14)
TypeError: Cannot read property 'headers' of undefined
    at GameServer.connectionEstablished (/home/ubuntu/workspace/src/GameServer.js:219:35)
    at emitTwo (events.js:106:13)
    at WebSocketServer.emit (events.js:191:7)
    at handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:88:16)
    at WebSocketServer.completeUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:197:10)
    at Server.WebSocketServer._ultron.on (/home/ubuntu/workspace/src/node_modules/ws/lib/WebSocketServer.js:87:14)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:409:14) 
I want to fix it .
i wanna use ogar not other projects.

**Comment by ItzLevvie** [comment]
@Faris90 Do you still want the fix?

**Comment by OfficialKake** [comment]
i want too

**Comment by ItzLevvie** [comment]
@Faris90 @OfficialKake

a) You can either remove this code https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L211-L230

b) Follow the instructions below on how to solve this issue properly.

1) Change https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L205 to ```function connectionEstablished(ws, req) {```
2) Change https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L219 to ```var origin = req.headers.origin;```

c) Change https://github.com/OgarProject/Ogar/blob/master/src/gameserver.ini#L28 to ```serverDiscardForeignClients = 0```

**Comment by OfficialKake** [comment]
thx
