### ISSUE TITLE
call back must be a function

### ISSUE THREAD

**Issue by khaledatef2002** [OgarProject/Ogar#713]
hello while iam tying to run the server from src/start.bat i have got erorr say callback must be a function
```
timers.js:379
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at setTimeout (timers.js:379:11)
    at GameServer.mainLoop (C:\Users\Administrator\Desktop\Ogar-master\src\GameServer.js:324:13)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

C:\Users\Administrator\Desktop\Ogar-master\src>pause
Press any key to continue . . .
```

**Comment by Luka967** [comment]
Ogar is very outdated. Use OgarII or MultiOgar-Edited instead.
Aside from it being outdated, you're probably using a newer version of node.js which broke Ogar.

**Comment by Faris90** [comment]
ItsLevvie says
Change https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L205 to function connectionEstablished(ws, req) {
Change https://github.com/OgarProject/Ogar/blob/master/src/GameServer.js#L219 to var origin = req.headers.origin;
c) Change https://github.com/OgarProject/Ogar/blob/master/src/gameserver.ini#L28 to serverDiscardForeignClients = 0
